 
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
    }
  public void enter()
  { 
      Color clr = new Color(0,51,51); 
             setBackground(clr);
      }
  public void exit()
  {
      Color clr = new Color(0,102,102);
              setBackground(clr);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_addfees = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnl_addrecord = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnl_addfees5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnl_addfees8 = new javax.swing.JPanel();
        pnl_addfees9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnl_addfees14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_addfees15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_searchrecord = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_addfees6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnl_addfees7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnl_addfees16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnl_addfees17 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pnl_addfees18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pnl_addfees19 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pnl_addfees10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnl_addfees11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_addfees12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pnl_addfees13 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_addfees.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfeesMouseExited(evt);
            }
        });
        pnl_addfees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/plus.png"))); // NOI18N
        jLabel4.setText("  Add Fees");
        jLabel4.setIconTextGap(0);
        pnl_addfees.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        jPanel1.add(pnl_addfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, 160));

        pnl_addrecord.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addrecordMouseExited(evt);
            }
        });
        pnl_addrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/grades.png"))); // NOI18N
        jLabel5.setText("Add Marks");
        pnl_addrecord.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 120));

        pnl_addfees5.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees5MouseExited(evt);
            }
        });
        pnl_addfees5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Fees");
        pnl_addfees5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addrecord.add(pnl_addfees5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        jPanel1.add(pnl_addrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 250, 160));

        pnl_addfees8.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addfees8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees8MouseExited(evt);
            }
        });
        pnl_addfees8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_addfees9.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees9MouseExited(evt);
            }
        });
        pnl_addfees9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Fees");
        pnl_addfees9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees8.add(pnl_addfees9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        pnl_addfees14.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees14MouseExited(evt);
            }
        });
        pnl_addfees14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        jLabel15.setText("Log Out");
        pnl_addfees14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pnl_addfees15.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees15MouseExited(evt);
            }
        });
        pnl_addfees15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Add Fees");
        pnl_addfees15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees14.add(pnl_addfees15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        pnl_addfees8.add(pnl_addfees14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 230, 90));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reports");
        pnl_addfees8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 40));

        jPanel1.add(pnl_addfees8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 460, 230, 90));

        pnl_searchrecord.setBackground(new java.awt.Color(0, 102, 102));
        pnl_searchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_searchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_searchrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_searchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_searchrecordMouseExited(evt);
            }
        });
        pnl_searchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search-document.png"))); // NOI18N
        jLabel3.setText("Search Record");
        jLabel3.setIconTextGap(0);
        pnl_searchrecord.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        jPanel1.add(pnl_searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 250, 160));

        pnl_addfees6.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addfees6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees6MouseExited(evt);
            }
        });
        pnl_addfees6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view report.png"))); // NOI18N
        jLabel7.setText("Attendance");
        pnl_addfees6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnl_addfees7.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees7MouseExited(evt);
            }
        });
        pnl_addfees7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Fees");
        pnl_addfees7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees6.add(pnl_addfees7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        jPanel1.add(pnl_addfees6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 250, 160));

        pnl_addfees16.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees16MouseExited(evt);
            }
        });
        pnl_addfees16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        jLabel17.setText("Log Out");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        pnl_addfees16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pnl_addfees17.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees17MouseExited(evt);
            }
        });
        pnl_addfees17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Add Fees");
        pnl_addfees17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees16.add(pnl_addfees17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        pnl_addfees18.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees18MouseExited(evt);
            }
        });
        pnl_addfees18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        jLabel19.setText("Log Out");
        pnl_addfees18.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pnl_addfees19.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees19MouseExited(evt);
            }
        });
        pnl_addfees19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Add Fees");
        pnl_addfees19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees18.add(pnl_addfees19, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        pnl_addfees16.add(pnl_addfees18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 230, 90));

        jPanel1.add(pnl_addfees16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 230, 90));

        pnl_addfees10.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addfees10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees10MouseExited(evt);
            }
        });
        pnl_addfees10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/text-book-opened-from-top-view.png"))); // NOI18N
        jLabel11.setText("Edit Course");
        pnl_addfees10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnl_addfees11.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees11MouseExited(evt);
            }
        });
        pnl_addfees11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Add Fees");
        pnl_addfees11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees10.add(pnl_addfees11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        jPanel1.add(pnl_addfees10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, 160));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rajiv Ghandhi Institute Of Technology");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -100, -1, -1));

        pnl_addfees12.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addfees12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees12MouseExited(evt);
            }
        });
        pnl_addfees12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit.png"))); // NOI18N
        jLabel22.setText("Student Detail  ");
        pnl_addfees12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 140));

        pnl_addfees13.setBackground(new java.awt.Color(0, 102, 102));
        pnl_addfees13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_addfees13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addfees13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addfees13MouseExited(evt);
            }
        });
        pnl_addfees13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Add Fees");
        pnl_addfees13.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pnl_addfees12.add(pnl_addfees13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 170));

        jPanel1.add(pnl_addfees12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 250, 160));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MANJARA   CHARITABLE   TRUST");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 490, 40));

        jLabel14.setFont(new java.awt.Font("Vivaldi", 3, 44)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rajiv Ghandhi Institute Of Technology");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 730, 60));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OFF.JUHU VERSOVA LINK ROAD ,VERSOVA,ANDHERI(W),MUMBAI-53,TEL:26707026/27/28 FAX:26707026");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 670, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1620, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 1395, 995);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_addfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfeesMouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees.setBackground(clr);
              // TODO add your handling code here:
                                            // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfeesMouseEntered

    private void pnl_addfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfeesMouseExited
         Color clr = new Color(0,102,102);
              pnl_addfees.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfeesMouseExited

    private void pnl_searchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_searchrecordMouseEntered
          Color clr = new Color(0,51,51); 
                 pnl_searchrecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_searchrecordMouseEntered

    private void pnl_searchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_searchrecordMouseExited
         Color clr = new Color(0,102,102);
              pnl_searchrecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_searchrecordMouseExited

    private void pnl_addfees5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees5MouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees5.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees5MouseEntered

    private void pnl_addfees5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees5MouseExited
        Color clr = new Color(0,102,102);
              pnl_addfees5.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees5MouseExited

    private void pnl_addrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addrecordMouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addrecord.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addrecordMouseEntered

    private void pnl_addrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addrecordMouseExited
        Color clr = new Color(0,102,102);
              pnl_addrecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addrecordMouseExited

    private void pnl_addfees7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees7MouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees7.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees7MouseEntered

    private void pnl_addfees7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees7MouseExited
        Color clr = new Color(0,102,102);
              pnl_addfees7.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees7MouseExited

    private void pnl_addfees6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees6MouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees6.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees6MouseEntered

    private void pnl_addfees6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees6MouseExited
        Color clr = new Color(0,102,102);
              pnl_addfees6.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees6MouseExited

    private void pnl_addfees9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees9MouseEntered
        Color clr = new Color(0,51,51); 
                 pnl_addfees9.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees9MouseEntered

    private void pnl_addfees9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees9MouseExited
        Color clr = new Color(0,102,102);
              pnl_addfees9.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees9MouseExited

    private void pnl_addfees8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees8MouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees8.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees8MouseEntered

    private void pnl_addfees8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees8MouseExited
        Color clr = new Color(0,102,102);
              pnl_addfees8.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees8MouseExited

    private void pnl_addfees15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees15MouseEntered
         Color clr = new Color(0,51,51); 
                 pnl_addfees15.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees15MouseEntered

    private void pnl_addfees15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees15MouseExited

    private void pnl_addfees14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees14MouseEntered

    private void pnl_addfees14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees14MouseExited

    private void pnl_addfees17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees17MouseEntered

    private void pnl_addfees17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees17MouseExited

    private void pnl_addfees19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees19MouseEntered

    private void pnl_addfees19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees19MouseExited

    private void pnl_addfees18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees18MouseEntered

    private void pnl_addfees18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees18MouseExited

    private void pnl_addfees16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees16MouseEntered

    private void pnl_addfees16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees16MouseExited

    private void pnl_addfees10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees10MouseExited
       Color clr = new Color(0,102,102); 
                 pnl_addfees10.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees10MouseExited

    private void pnl_addfees10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees10MouseEntered
       Color clr = new Color(0,51,51); 
                 pnl_addfees10.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees10MouseEntered

    private void pnl_addfees11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees11MouseExited

    private void pnl_addfees11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees11MouseEntered

    private void pnl_addfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfeesMouseClicked
               Add_Fees x = new Add_Fees();
               x.setVisible(true);
               this.setVisible(false);
                 // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfeesMouseClicked

    private void pnl_searchrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_searchrecordMouseClicked
         SearchRecord sr =new SearchRecord();
                 sr.setVisible(true);
                 this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pnl_searchrecordMouseClicked

    private void pnl_addfees10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees10MouseClicked
           add_Course ac = new add_Course();
           ac.show();
           this.dispose();
              // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees10MouseClicked

    private void pnl_addrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addrecordMouseClicked
                     Add_marks vr =new Add_marks();
                          vr.show();
                          this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addrecordMouseClicked

    private void pnl_addfees6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees6MouseClicked
                   Add_Atdn rg =new  Add_Atdn();
                            rg.show();
                            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees6MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
              this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void pnl_addfees8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees8MouseClicked
               ReportGenerate rg = new  ReportGenerate();
               rg.setVisible(true);
                  this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees8MouseClicked

    private void pnl_addfees13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees13MouseEntered

    private void pnl_addfees13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees13MouseExited

    private void pnl_addfees12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees12MouseClicked
std kg =new std ();
               kg.setVisible(true);
                  this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees12MouseClicked

    private void pnl_addfees12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees12MouseEntered

    private void pnl_addfees12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addfees12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_addfees12MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_addfees;
    private javax.swing.JPanel pnl_addfees10;
    private javax.swing.JPanel pnl_addfees11;
    private javax.swing.JPanel pnl_addfees12;
    private javax.swing.JPanel pnl_addfees13;
    private javax.swing.JPanel pnl_addfees14;
    private javax.swing.JPanel pnl_addfees15;
    private javax.swing.JPanel pnl_addfees16;
    private javax.swing.JPanel pnl_addfees17;
    private javax.swing.JPanel pnl_addfees18;
    private javax.swing.JPanel pnl_addfees19;
    private javax.swing.JPanel pnl_addfees5;
    private javax.swing.JPanel pnl_addfees6;
    private javax.swing.JPanel pnl_addfees7;
    private javax.swing.JPanel pnl_addfees8;
    private javax.swing.JPanel pnl_addfees9;
    private javax.swing.JPanel pnl_addrecord;
    private javax.swing.JPanel pnl_searchrecord;
    // End of variables declaration//GEN-END:variables

    private static class pnl_addfees {

        private static void setBackground(Color clr) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public pnl_addfees() {
        }
    }
}
