
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lbl_password.setVisible(false);
             lbl_username.setVisible(false);
             txt_password.setVisible(false);
             txt_username.setVisible(false);
             btn_signup.setVisible(false);
    }

    
    
          void userVerification(String username,String password ) //throws ClassNotFoundException, SQLException
          {
            try{  
          Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         Connection conn =DriverManager.getConnection("jdbc:derby://localhost:1527/login","root","root");
         String sql="select * from SIGNUP where USERNAME=? and PASSWORD=? ";
         PreparedStatement pst=conn.prepareStatement(sql);
         pst.setString(1, username);
         pst.setString(2,password );
         ResultSet rs =pst.executeQuery();
         if(rs.next())
         {
         Home_page home =new Home_page();
         home.show();
         this.dispose();
         }    
         else
         {
             JOptionPane.showMessageDialog(this, "username or passwword is incorrect");
         }         
         
          } 
          catch(Exception e)
          {
          }
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_exit = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        login = new javax.swing.JComboBox<>();
        lbl_pnr = new javax.swing.JLabel();
        txt_pnr = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 103, 103));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log In");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 152, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username :");
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 117, -1));

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("Select User :");
        jPanel2.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 270, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 270, -1));

        btn_exit.setBackground(new java.awt.Color(0, 103, 103));
        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 100, -1));

        btn_login.setBackground(new java.awt.Color(0, 103, 103));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        btn_signup.setBackground(new java.awt.Color(0, 102, 102));
        btn_signup.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Admin" }));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 44, 270, 42));

        lbl_pnr.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_pnr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pnr.setText("PNR No :");
        jPanel2.add(lbl_pnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 137, 133, 30));

        txt_pnr.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txt_pnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pnrActionPerformed(evt);
            }
        });
        jPanel2.add(txt_pnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 133, 270, 40));

        lbl_password.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Password :");
        jPanel2.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 176, 117, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
         String username =txt_username.getText();
         String password =txt_password.getText();
        if(login.getSelectedIndex()==1) {
   if(username.trim().equals("")||password.trim().equals(""))
   {
   JOptionPane.showMessageDialog(this, "please enter  username and passwword ");
   
   }
   else
   {
       userVerification( username, password );
   }
        }else{
             Studenthomepage tb =new  Studenthomepage();
            tb.setVisible(true);
            setVisible(false);
            tb.PNR.setText(txt_pnr.getText());
        }




// TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
       signup x= new signup();
       x.setVisible(true);
       setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
      this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
             if ( login.getSelectedIndex()==0) {
             lbl_pnr.setVisible(true);
             txt_pnr.setVisible(true);
             lbl_password.setVisible(false);
             lbl_username.setVisible(false);
             txt_password.setVisible(false);
             txt_username.setVisible(false);
             btn_signup.setVisible(false);
             } 
             else {
                 lbl_pnr.setVisible(false);
             txt_pnr.setVisible(false);
             lbl_password.setVisible(true);
             lbl_username.setVisible(true);
             txt_password.setVisible(true);
             txt_username.setVisible(true);
               btn_signup.setVisible(true);
               
             } 
// TODO add your handling code here:
                            // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void txt_pnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pnrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_pnr;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JComboBox<String> login;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_pnr;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
