
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Print_receipt extends javax.swing.JFrame {

    /**
     * Creates new form Print_receipt
     */
    public Print_receipt() {
        initComponents();
      getData();
    }
    
    
    public void getData()
    {
        try
        {
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         Connection conn =DriverManager.getConnection("jdbc:derby://localhost:1527/login","root","root");
         PreparedStatement pst = conn.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
         ResultSet rs = pst.executeQuery();
         rs.next();
         txt_receiptNo.setText(rs.getString("reciept_no"));
         txt_name.setText(rs.getString("student_name"));
         txt_branch.setText(rs.getString("branch_name"));
         txt_class.setText(rs.getString("course_name"));
         txt_rollNo1.setText(rs.getString("roll_no"));
         txt_date.setText(rs.getString("date"));
         txt_amount.setText(rs.getString("amount"));
         txt_cgst.setText(rs.getString("cgst"));
         txt_sgst.setText(rs.getString("sgst"));
         txt_totalAmount.setText(rs.getString("total_amount"));
         txt_words.setText(rs.getString("total_in_words"));
         //txt_remaining.setText(rs.getString("remianing"));
         txt_remark.setText(rs.getString("remark"));
           
         String a = rs.getString("payment_mode");
         if(a.equalsIgnoreCase("cash"))
         {
             lbl_dd.setText("");
             lbl_bank.setText("");
             txt_bank.setText("");
             txt_dd.setText("");
         }
         
         
         if(a.equalsIgnoreCase("DD"))
         {
             lbl_dd.setText("DDNo :");
             lbl_bank.setText("Bank Name");
             txt_bank.setText(rs.getString("bank_name"));
             txt_dd.setText(rs.getString("dd_no"));
         }
         if(a.equalsIgnoreCase("Cheque"))
         {
             lbl_dd.setText("ChequeNo :");
             lbl_bank.setText("Bank Name");
             txt_bank.setText(rs.getString("bank_name"));
             txt_dd.setText(rs.getString("cheque_no"));
         }
         if(a.equalsIgnoreCase("Card"))
         {
             lbl_dd.setText("");
             lbl_bank.setText("Bank Name");
             txt_bank.setText(rs.getString("bank_name"));
             txt_dd.setText("");
         }
         
         
         
         jLabel38.setText(rs.getString("course_name")+""+rs.getString("branch_name")+" Tution Fees");
         
         
        }
        catch(Exception e)
        {
        }
    }
 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnl_print = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        txt_rollNo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_totalAmount = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_class = new javax.swing.JLabel();
        txt_branch = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_words = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txt_rollNo1 = new javax.swing.JLabel();
        lbl_dd = new javax.swing.JLabel();
        lbl_bank = new javax.swing.JLabel();
        txt_dd = new javax.swing.JLabel();
        txt_bank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_sidebar.setBackground(new java.awt.Color(0, 102, 102));
        pnl_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        jLabel1.setText("Logout");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel4.setText("Home");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 70));

        pnl_sidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 330, 70));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/printer-.png"))); // NOI18N
        jLabel2.setText("Print");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        pnl_sidebar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 330, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search2.png"))); // NOI18N
        jLabel3.setText("Search Record");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        pnl_sidebar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 330, 70));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel5.setText("Edit Receipt");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel6.setText("Home");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 70));

        pnl_sidebar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 330, 70));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/list_1.png"))); // NOI18N
        jLabel7.setText("Course List");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel8.setText("Home");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 70));

        pnl_sidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 330, 70));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view all record.png"))); // NOI18N
        jLabel9.setText("View Record");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel10.setText("Home");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 70));

        pnl_sidebar.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 330, 70));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/left-arrow.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel12.setText("Home");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, 70));

        pnl_sidebar.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 330, 70));

        getContentPane().add(pnl_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 741));

        pnl_print.setBackground(new java.awt.Color(255, 255, 255));
        pnl_print.setMinimumSize(new java.awt.Dimension(600, 700));
        pnl_print.setPreferredSize(new java.awt.Dimension(600, 700));
        pnl_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel13.setText("MANJARA   CHARITABLE   TRUST");
        pnl_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 490, 40));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 510, 860, 20));

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        pnl_print.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 860, 10));

        jLabel14.setFont(new java.awt.Font("Vivaldi", 3, 44)); // NOI18N
        jLabel14.setText("Rajiv Ghandhi Institute Of Technology");
        pnl_print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 730, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("OFF.JUHU VERSOVA LINK ROAD ,VERSOVA,ANDHERI(W),MUMBAI-53,TEL:26707026/27/28 FAX:26707026");
        pnl_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 670, 30));

        txt_receiptNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_receiptNo.setText("Receipt No.");
        pnl_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        txt_rollNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_rollNo.setText("Name Of Student  :");
        pnl_print.add(txt_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Class :");
        pnl_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Amount(Rs)");
        pnl_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("PNR No :");
        pnl_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Signature");
        pnl_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Total Amount :");
        pnl_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Branch :");
        pnl_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 860, 10));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Sr No");
        pnl_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Head");
        pnl_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, 40));

        txt_remark.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_remark.setText("Remark :");
        pnl_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 280, 30));

        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_amount.setText("Total Amount :");
        pnl_print.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, 30));

        txt_cgst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_cgst.setText("Total Amount :");
        pnl_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 140, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Total  in words:");
        pnl_print.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 40));

        txt_totalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_totalAmount.setText("Total Amount :");
        pnl_print.add(txt_totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 140, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("CGST  ");
        pnl_print.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("SGST");
        pnl_print.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, 30));

        txt_sgst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_sgst.setText("Total Amount :");
        pnl_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 140, 30));

        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 860, 20));

        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 860, 20));

        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 220, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Date :");
        pnl_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Receipt No.");
        pnl_print.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Name Of Student  :");
        pnl_print.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_name.setText("Name Of Student  :");
        pnl_print.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 250, -1));

        txt_class.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_class.setText("Name Of Student  :");
        pnl_print.add(txt_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 202, 250, 20));

        txt_branch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_branch.setText("Name Of Student  :");
        pnl_print.add(txt_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 250, -1));

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_date.setText("Name Of Student  :");
        pnl_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 140, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Total Amount :");
        pnl_print.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, 30));

        txt_words.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_words.setText("Total Amount :");
        pnl_print.add(txt_words, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 410, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("Remark :");
        pnl_print.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 90, 30));

        txt_rollNo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_rollNo1.setText("Name Of Student  :");
        pnl_print.add(txt_rollNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 100, -1));

        lbl_dd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_dd.setText("Name Of Student  :");
        pnl_print.add(lbl_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 100, -1));

        lbl_bank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_bank.setText("Bank  Name:");
        pnl_print.add(lbl_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));

        txt_dd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_dd.setText("Name Of Student  :");
        pnl_print.add(txt_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 100, -1));

        txt_bank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_bank.setText("Name Of Student  :");
        pnl_print.add(txt_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 100, -1));

        getContentPane().add(pnl_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 25, 860, 670));

        setSize(new java.awt.Dimension(1403, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.72,1.07);
                
                pnl_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
                Edit_print ep = new  Edit_print();
                  ep.setVisible(true);
                      this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Home_page hp =new  Home_page();
        hp.setVisible(true);
                      this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_receipt().setVisible(true);
            }
        });
    }
             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bank;
    private javax.swing.JLabel lbl_dd;
    private javax.swing.JPanel pnl_print;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_bank;
    private javax.swing.JLabel txt_branch;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_class;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_dd;
    private javax.swing.JLabel txt_name;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rollNo;
    private javax.swing.JLabel txt_rollNo1;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_totalAmount;
    private javax.swing.JLabel txt_words;
    // End of variables declaration//GEN-END:variables

}
