/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Record_Details extends javax.swing.JFrame {

    /**
     * Creates new form Record_Details
     */
    public Record_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_remark = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_branch = new javax.swing.JLabel();
        lbl_category = new javax.swing.JLabel();
        lbl_ttlam = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        lbl_rem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setPreferredSize(new java.awt.Dimension(780, 480));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Category :");
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Remark :");
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Name :");
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Branch :");
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("ID :");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Course :");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Total Amount :");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 160, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Remaining :");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 40));

        lbl_remark.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 220, 40));

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, 40));

        lbl_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 40));

        lbl_branch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 40));

        lbl_category.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 40));

        lbl_ttlam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_ttlam, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 220, 40));

        lbl_course.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 220, 40));

        lbl_rem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel13.add(lbl_rem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 220, 40));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        setBounds(100, 50, 789, 480);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Record_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel13;
    public javax.swing.JLabel lbl_branch;
    public javax.swing.JLabel lbl_category;
    public javax.swing.JLabel lbl_course;
    public javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_name;
    public javax.swing.JLabel lbl_rem;
    public javax.swing.JLabel lbl_remark;
    public javax.swing.JLabel lbl_ttlam;
    // End of variables declaration//GEN-END:variables
}
